# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [1]:
import numpy as np
ar1=np.random.randint(10,22,22)
ar2=np.array(ar1)
print(ar2)


[21 13 19 16 21 10 11 19 18 19 12 17 13 13 16 13 15 13 19 17 14 13]


##### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [12]:
ar3=np.arange(1,50,2)
print(ar3)
print(len(ar3))




[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [13]:
ar4=np.linspace(4,7,27)
print(ar4)



[4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [6]:
mat=np.random.random((5,4))
print(np.round(mat,2))




[[0.47 0.02 0.22 0.03]
 [0.94 0.21 0.75 0.19]
 [0.66 0.9  0.87 0.44]
 [0.04 0.92 0.35 0.71]
 [0.74 0.61 0.09 0.46]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [14]:
ar6=np.random.randint(5,15,(5,5))
print(ar6)




[[13 13 10  7 10]
 [14 11  7 14  5]
 [ 9  7  5 10  6]
 [ 7  5 12 11  8]
 [10 14 11 10  8]]


#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [8]:
oned_ar=np.zeros(5,dtype=np.float32)
print(oned_ar,oned_ar.dtype)



[0. 0. 0. 0. 0.] float32


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [9]:
twod_ar=np.ones((5,4),dtype=np.float32)
print(twod_ar,twod_ar.dtype)




[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] float32


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [5]:
mat1=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(mat1.shape)
print(mat1.dtype)
print(type(mat1))

(5, 5)
int64
<class 'numpy.ndarray'>


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [6]:
y=mat1.flatten()
mid=y[int(len(y)/2)]
print("The center pixeel of matrix is",mid)




The center pixeel of matrix is 3


#### 10. Print the all the elements of 3rd row of the matrix

In [19]:
print(mat1[2,:])




[ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [20]:
print(mat1[:,3])



[34 65 76 54  5]


#### 12. Print the 4 corner pixels of the matrix

In [22]:
print(mat1[3:,3:])




[[54  6]
 [ 5  8]]


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [8]:
m1=np.array([[50,34],[34,65]])
m3=np.array([[3,76,3],[6,54,6],[8,5,8]])
m2=np.array([[7,8],[23,12]])




#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [40]:
r1=m1.reshape(4,1)
print(r1)
r2=m2.reshape(9,1)
print(r2)
r3=m3.reshape(4,1)
print(r3)


[[50]
 [34]
 [34]
 [65]]
[[ 3]
 [76]
 [ 3]
 [ 6]
 [54]
 [ 6]
 [ 8]
 [ 5]
 [ 8]]
[[ 7]
 [ 8]
 [23]
 [12]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [9]:
c1=np.concatenate((m1,m2),axis=0)
c2=np.concatenate((m1,m2),axis=1)
print(c1)
print(c2)



[[50 34]
 [34 65]
 [ 7  8]
 [23 12]]
[[50 34  7  8]
 [34 65 23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [10]:
print(m1+m2)
print(m1-m2)
print(m1*m2)
print(m1/m2)




[[57 42]
 [57 77]]
[[43 26]
 [11 53]]
[[350 272]
 [782 780]]
[[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [16]:
m31=m3[1:3,0:2]
print(m1+m31)



[[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [35]:
mean1=m1[:,0].mean()
mean2=m1[:,1].mean()
r1=np.array([[mean1,mean2]])
m4=np.concatenate((r1,m1),axis=0)
print(m4)


[[42.  49.5]
 [50.  34. ]
 [34.  65. ]]


#### 19. Perform the matrix multiplication between m3 and m4

In [38]:
print(np.matmul(m3,m4))




[[4028.  2927.5]
 [3156.  2523. ]
 [ 858.  1086. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [28]:
me1=mat1[0,:].mean()
var1=mat1[0,:].var()
std1=mat1[0,:].std()
me2=mat1[1,:].mean()
var2=mat1[1,:].var()
std2=mat1[1,:].std()
me3=mat1[2,:].mean()
var3=mat1[2,:].var()
std3=mat1[2,:].std()
me4=mat1[3,:].mean()
var4=mat1[3,:].var()
std4=mat1[3,:].std()
me5=mat1[4,:].mean()
var5=mat1[4,:].var()
std5=mat1[4,:].std()
print(max(me1,var1,std1))
print(min(me1,var1,std1))
print(max(me2,var2,std2))
print(min(me2,var2,std2))
print(max(me3,var3,std3))
print(min(me3,var3,std3))
print(max(me4,var4,std4))
print(min(me4,var4,std4))
print(max(me5,var5,std5))
print(min(me5,var5,std5))

214.64000000000001
14.65059725744995
548.24
23.414525406251563
820.1600000000001
18.8
357.75999999999993
16.2
39.760000000000005
6.305553108173779


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [30]:
runs=np.array([['MSD',54,60,10,65],['Kholi',102,2,78,32],['Rohit',3,110,1,92],['Rahul',56,6,12,42],['Dhawan',12,8,22,11]])
balls=np.array([['MSD',50,42,22,78],['Kholi',95,8,65,43],['Rohit',9,100,7,101],['Rahul',27,3,11,31],['Dhawan',24,20,36,27]])
runs=runs[:,1:].astype(int)
balls=balls[:,1:].astype(int)
avg1=runs[0:,:]/4
strike_rate=(runs/balls)*100
print(avg1)
sort_strikerate=np.sort(strike_rate)[::-1]
print(sort_avg)
print(sort_strikerate)

[[13.5  15.    2.5  16.25]
 [25.5   0.5  19.5   8.  ]
 [ 0.75 27.5   0.25 23.  ]
 [14.    1.5   3.   10.5 ]
 [ 3.    2.    5.5   2.75]]
[[ 2.    2.75  3.    5.5 ]
 [ 1.5   3.   10.5  14.  ]
 [ 0.25  0.75 23.   27.5 ]
 [ 0.5   8.   19.5  25.5 ]
 [ 2.5  13.5  15.   16.25]]
[[ 40.          40.74074074  50.          61.11111111]
 [109.09090909 135.48387097 200.         207.40740741]
 [ 14.28571429  33.33333333  91.08910891 110.        ]
 [ 25.          74.41860465 107.36842105 120.        ]
 [ 45.45454545  83.33333333 108.         142.85714286]]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [3]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
pass_stud=marks[marks>50]
fail_stud=marks[marks<50]
print("The number of students passed are",len(pass_stud))
print("The number of students failed are",len(fail_stud))



The number of students passed are 7
The number of students failed are 3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [4]:
ind=np.where((marks > 45) & (marks < 49))
marks[ind]=marks[ind]+5
ind1=np.where((marks >80))
marks[ind1]=marks[ind1]+5
ind2=np.where((marks>100))
marks[ind2]=100
print(marks)




[ 65  89  52  56  94 100  53  77  80  39]


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [1]:
import time
def lis():
    x=list(range(1,60000))
    y=list(range(1,60000))
    res=[]
    for i in range(len(x)):
        res.append((((x[i]**2)+8)/y[i]))
def npy():
    x=np.array(range(1,60000))
    y=np.array(range(1,60000))
    res=((x**2)+8)/y
start=time.time()
end=time.time()
print("The time taken for list is",end-start)
start1=time.time()
end1=time.time()
print("The time taken for numpy is",end1-start1)



The time taken for list is 2.6941299438476562e-05
The time taken for numpy is 3.3855438232421875e-05


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.







